relays/urls.py
from django.urls import path

from . import views

app_name = 'relays'

urlpatterns = [
    path('', views.index, name='index'),
    path('server/<int:server>', views.server, name='server'),
]

relays/templates/relays/base-bs5.html
{% extends "allianceauth/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block page_title %}
    {% translate "Relays" %}
{% endblock page_title %}

{% block header_nav_brand %}
    <a class="navbar-brand" href="{% url 'relays:index' %}">{% translate "Relays" %}</a>
{% endblock header_nav_brand %}
{% block header_nav_collapse_left %}
{% endblock header_nav_collapse_left %}

{% block header_nav_collapse_right %}
{% endblock header_nav_collapse_right %}

{% block content %}
{% endblock content %}

relays/templates/relays/index-bs5.html
{% extends "relays/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% block content %}
    <div class="row row-cols-1 row-cols-md-3 row-cols-lg-6 g-2">
        {% for server in servers %}
            <div class="col">
                <div class="card h-100">
                    <div class="card-header">
                        <h5 class="card-title">{{ server.name }}</h5>
                    </div>
                    <div class="card-body">
                        {% translate "Protocol" %}:<span class="badge bg-secondary">{{ server.protocol }}</span>
                        <br />
                        {% translate "Channels" %}:<span class="badge bg-secondary">{{ server.channel_count|intcomma }}</span>
                        <br />
                        {% translate "Users" %}:<span class="badge bg-secondary">{{ server.users|intcomma }}</span>
                        <br />
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'relays:server' server.server %}"><span class="btn btn-primary" role="button">{% translate "View Messages" %}: <span class="badge bg-secondary">{{ server.message_count|intcomma }}</span></a></span>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

relays/templates/relays/server-bs5.html
{% extends "relays/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% block content %}
    <div class="card card-success col-lg-12 container-fluid">
        <div class="card-header">
            <span class="card-title">{% translate "Server" %}: {{ server.name }}</span>
        </div>
        <div class="card-body">{% include "relays/server_messages-bs5.html" %}</div>
    </div>
{% endblock content %}
{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
    {% include "bundles/moment-js.html" with locale=True %}
{% endblock extra_javascript %}

{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock extra_css %}
{% block extra_script %}
new DataTable('#table-server-messages', {
    ajax: '/relays/api/datatables_server_messages/{{ server.server }}',
    processing: true,
    serverSide: true,
    stateSave: true,
    });
{% endblock extra_script %}

relays/templates/relays/server_messages-bs5.html
{% load i18n %}
{% load humanize %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">{% translate "Server Messages" %}</h3>
    </div>
    <div class="panel-body">
        <table class="table table-responsive" id="table-server-messages" style="width: 100%;">
            <thead>
                <tr>
                    <th class="text-left">{% translate "Sent" %}</th>
                    <th class="text-left">{% translate "Channel" %}</th>
                    <th class="text-left">{% translate "Username" %}</th>
                    <th class="text-left">{% translate "Content" %}</th>
                </tr>
            </thead>
        </table>
    </div>
</div>